--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/hugo/Pictures/Wallpapers/k-onWallpaper.jpeg"

-- Special
background="#0c1c1f"
foreground="#e2d9cb"
cursor="#e2d9cb"

-- Colors
color0="#0c1c1f"
color1="#996563"
color2="#9F8D72"
color3="#687980"
color4="#3E8385"
color5="#649591"
color6="#9BA393"
color7="#e2d9cb"
color8="#9e978e"
color9="#996563"
color10="#9F8D72"
color11="#687980"
color12="#3E8385"
color13="#649591"
color14="#9BA393"
color15="#e2d9cb"
