# Shell variables
# Generated by 'wal'
wallpaper='/home/hugo/Pictures/Wallpapers/k-onWallpaper.jpeg'

# Special
background='#0c1c1f'
foreground='#e2d9cb'
cursor='#e2d9cb'

# Colors
color0='#0c1c1f'
color1='#996563'
color2='#9F8D72'
color3='#687980'
color4='#3E8385'
color5='#649591'
color6='#9BA393'
color7='#e2d9cb'
color8='#9e978e'
color9='#996563'
color10='#9F8D72'
color11='#687980'
color12='#3E8385'
color13='#649591'
color14='#9BA393'
color15='#e2d9cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
