#!/bin/zsh

WALL_DIR="$HOME/Pictures/Wallpapers"

CWD="$(pwd)"

cd "$WALL_DIR" || exit

IFS=$'\n'

SELECTED_WALL=$(for a in *.jpeg *.png; do echo -en "$a\0icon\x1f$a\n" ; done | rofi -dmenu -theme /home/hugo/.config/rofi/wallpaper/config.rasi)

if [ -n "$SELECTED_WALL" ]; then
  /home/hugo/.config/hypr/scripts/walset-backend "$SELECTED_WALL"
fi

  cd "$CMD" || exit
